export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const LOAD_SINGLEGAME_SUCCESS = 'LOAD_SINGLEGAME_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const GET_INPUT_VALUE = 'GET_INPUT_VALUE'