export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const LOAD_SINGLEGAME_SUCCESS = 'LOAD_SINGLEGAME_SUCCESS';
export const LOAD_SINGLEGAMECOVER_SUCCESS = 'LOAD_SINGLEGAMECOVER_SUCCESS'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const ERROR_MESSAGE = 'ERROR_MESSAGE'
export const ADD_WISHLIST = 'ADD_WISHLIST'
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM'
